version: '3'

services:
  web:
    build: .
    command: python3 BestStore/manage.py runserver 0.0.0.0:8000
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
